// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorExtensionsDemo
{
    internal sealed partial class Vsix
    {
        public const string Id = "EditorExtensionsDemo.39123d92-ffe7-4158-9595-740d2745d46c";
        public const string Name = "EditorExtensionsDemo";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tony Hallett";
        public const string Tags = "";
    }
}
