// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorExtensionsDemo
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorExtensionsDemoString = "47088d12-3fd3-4c36-b486-885b33fb16f4";
        public static Guid EditorExtensionsDemo = new Guid(EditorExtensionsDemoString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int ShowClassificationWindowCommand = 0x0101;
    }
}